### ISSUE TITLE
Dynamic items from GlobalContext are null in loggly.

### ISSUE THREAD

**Issue by vvolodin** [loggly/log4net-loggly#13]
Dynamic items added to GlobalContext aren't being processed correctly. If I add an instance of my class there, ToString() doesn't seem to be invoked on it during logging.

**Comment by mostlyjason** [comment]
Okay thanks for reporting this. We have many other issues in the queue ahead of this one so if you find a fix before us please let us know.

**Comment by Katulus** [comment]
@vvolodin , the logger does not call `ToString()` on values in contexts, it serializes their properties to JSON. If you want to call `ToString()` you can use `IFixingRequired` interface on your class. Logger then uses that to "fix" the value during logging.

```csharp
private class FixedClass : IFixingRequired
{
    public int Property1 { get; set; }
    public int Property2 { get; set; }

    public object GetFixedObject()
    {
        return ToString();
    }

    public override string ToString()
    {
        return "This will be in the logged output";
    }
}

GlobalContext.Properties["MyProperty"] = new FixedClass();
```
Now when you log something the JSON sent to Loggly will contain:
```json
{
  "MyProperty": "This will be in the logged output",
   // other properties
}
```
