### ISSUE TITLE
Should I call Shutdown on each logger instance?

### ISSUE THREAD

**Issue by chester89** [loggly/log4net-loggly#22]
Hello. 
I'm using log4net loggly in several projects and recently noticed that not all of my messages show up on the dashboard (the last few of them weren't there). I waited a long time and there's no sign of them, so it's unlikely to be a service issue.
I found in the docs I should call `logger.Logger.Repository.Shutdown();` before exiting the application. I use separate logger instance for each of my classes. Should I call `Shutdown` only once for the entire app or for each of those separate logger instances?

I use 7.2.3 for the moment.

**Comment by chester89** [comment]
@Katulus @mostlyjason

**Comment by Katulus** [comment]
Hi @chester89,
`logger.Logger.Repository.Shutdown();` should properly shutdown everything so it's enough to call it just once. But the shutdown for `log4net-loggly` works properly only in latest `9.0.0-beta1` so make sure you use that.

**Comment by chester89** [comment]
I see. Calling `Shutdown()` once for the whole app solved my problems on 7.x, but I'll  upgrade in near future. Thanks.

**Comment by DreadedTuba** [comment]
> Hi @chester89, `logger.Logger.Repository.Shutdown();` should properly shutdown everything so it's enough to call it just once. But the shutdown for `log4net-loggly` works properly only in latest `9.0.0-beta1` so make sure you use that.

you have no idea how long I spent to find this ... I could not figure out why Shutdown() wasn't working with version 8, I mean surely Shutdown works in version 8, right?  Let it be a reminder to use the latest version...
