### ISSUE TITLE
.NET Standard 1.x

### ISSUE THREAD

**Issue by anton-bannerflow** [loggly/log4net-loggly#5]
Hi guys,
Could you please add support of .NET Standard 1.x? 
It would be very useful for those who want to use Loggly on Linux from .net

**Comment by mostlyjason** [comment]
This is a great suggestion! Leaving this issue open to see if other customers want this support as well.

**Comment by mhsmith01** [comment]
+1 on the request.  Found some work arounds on config loading given new AppSettings.json with projects but the main blocker has been with  LogicalThreadContext:

log4net:ERROR [LogglyAppender] ErrorCode: GenericFailure. Failed in DoAppend
System.TypeLoadException: Could not load type 'log4net.LogicalThreadContext' from assembly 'log4net, Version=2.0.7.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'.
   at log4net.loggly.LogglyFormatter.PreParse(LoggingEvent loggingEvent)
   at log4net.loggly.LogglyFormatter.ToJson(LoggingEvent loggingEvent)
   at log4net.loggly.LogglyAppender.SendLogAction(LoggingEvent loggingEvent)
   at log4net.loggly.LogglyAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)

Some context on others impacted: https://stackoverflow.com/questions/6939037/log4net-logicalthreadcontext-not-working

**Comment by peader** [comment]
+1 on support for net standard

**Comment by Shwetajain148** [comment]
Hey everyone! The .NET Standard 2.0 support has been added in the library. Please refer the related PR- #18 and nuget update [here](https://www.nuget.org/packages/log4net-loggly/8.0.1).

Closing this issue.

Thanks!
